# Generated by Django 3.2.16 on 2023-01-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20230123_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsRequest',
        ),
    ]
