# Generated by Django 3.2.16 on 2023-01-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_friendsrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsRequest',
        ),
    ]
