# Generated by Django 3.2.16 on 2023-02-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0006_friendsrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsrequest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.CreateModel(
            name='UserProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_pic', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_pic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfilePics',
                'verbose_name_plural': 'UserProfilePics',
            },
        ),
    ]
