# Generated by Django 3.2.16 on 2023-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20230201_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.FileField(upload_to='profilePicture/'),
        ),
    ]
