# Generated by Django 3.2.16 on 2023-02-01 07:52

import apps.user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_userprofilepic_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_pic',
            field=models.FileField(upload_to=apps.user_profile.models.user_directory_path),
        ),
    ]
