# Generated by Django 3.2.16 on 2023-02-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20230201_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfileInfo', 'verbose_name_plural': 'UserProfileInfos'},
        ),
    ]
