# Generated by Django 3.2.16 on 2023-01-20 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpersonalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
