# Generated by Django 3.2.16 on 2023-02-24 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20230214_0924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersaved',
            unique_together={('user', 'post')},
        ),
    ]
